# Generated by Django 5.1.6 on 2026-03-27 13:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0022_delete_courseannouncement'),
        ('users_calendar', '0005_coursecalendarevent_course_test_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Sent at')),
                ('notification_type', models.CharField(choices=[('event_reminder', 'Event reminder'), ('message_from_course_owner', 'Message from course owner'), ('achievement_unlocked', 'Achievement unlocked'), ('default', 'Default')], default='default', max_length=50, verbose_name='Notification type')),
                ('is_important', models.BooleanField(default=False, verbose_name='Is important')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is read')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(blank=True, default='', max_length=1000, verbose_name='Message')),
                ('personal_link', models.URLField(blank=True, null=True, verbose_name='External Link')),
                ('link_text', models.CharField(blank=True, default='', help_text='Текст на кнопці для персонального посилання', max_length=50, verbose_name='Link Text')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.course', verbose_name='Course')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='users_calendar.personalevent', verbose_name='Personal event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-sent_at'], name='notificatio_user_id_698af8_idx'), models.Index(fields=['-sent_at'], name='notificatio_sent_at_307610_idx')],
            },
        ),
    ]
