# ????? ?? ???? ???????
sonar.projectKey=SmartStudyBackend
sonar.projectName=SmartStudyBackend

# ???? ?? ???????? ?????
sonar.sources=.

# URL ???????
sonar.host.url=http://localhost:9000

# ?????, ???? ?? ??????????
sonar.login=sqb_307c8185bc9ccb69e3e57324f1f4b6ddce8339bc

## ???????? ??????? (???????????)
#sonar.python.coverage.reportPaths=coverage.xml
