# Generated by Django 5.1.6 on 2025-09-06 10:54

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Course title')),
                ('description', models.TextField(max_length=1000, verbose_name='Course description')),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('data_science', 'Data Science'), ('design', 'Design'), ('marketing', 'Marketing'), ('business', 'Business'), ('personal_development', 'Personal Development'), ('health_fitness', 'Health & Fitness'), ('music', 'Music'), ('photography', 'Photography'), ('language_learning', 'Language Learning')], db_index=True, max_length=100, verbose_name='Category')),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True, verbose_name='Cover image URL')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Is published')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Course version')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Course owner')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Issued at')),
                ('certificate_id', models.CharField(max_length=100, unique=True, verbose_name='Certificate ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Is valid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Announcement title')),
                ('content', models.TextField(verbose_name='Announcement content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_important', models.BooleanField(default=False, verbose_name='Is important')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Announcement',
                'verbose_name_plural': 'Course Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_structure', models.JSONField(blank=True, default=list, verbose_name='Course structure')),
                ('total_modules', models.PositiveIntegerField(default=0, verbose_name='Total modules')),
                ('total_lessons', models.PositiveIntegerField(default=0, verbose_name='Total lessons')),
                ('total_tests', models.PositiveIntegerField(default=0, verbose_name='Total tests')),
                ('time_to_complete', models.DurationField(default=datetime.timedelta(0), verbose_name='Time to complete course')),
                ('course_language', models.CharField(default='English', max_length=50, verbose_name='Course language')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Course rating')),
                ('level', models.CharField(choices=[('starting', 'Starting'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, max_length=100, verbose_name='Course level')),
                ('number_completed', models.PositiveIntegerField(default=0, verbose_name='Count is completed course')),
                ('number_of_active', models.PositiveIntegerField(default=0, verbose_name='Count active course')),
                ('feedback_count', models.PositiveIntegerField(default=0, verbose_name='Review count')),
                ('feedback', models.JSONField(blank=True, default=dict, verbose_name='Feedback')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course detail',
                'verbose_name_plural': 'Course details',
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1-5)')),
                ('comment', models.TextField(max_length=1000, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is verified')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Course Review',
                'verbose_name_plural': 'Course Reviews',
            },
        ),
        migrations.CreateModel(
            name='CourseVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', models.UUIDField(verbose_name='Original course ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Version number')),
                ('title', models.CharField(max_length=100, verbose_name='Course title')),
                ('description', models.TextField(max_length=1000, verbose_name='Course description')),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('data_science', 'Data Science'), ('design', 'Design'), ('marketing', 'Marketing'), ('business', 'Business'), ('personal_development', 'Personal Development'), ('health_fitness', 'Health & Fitness'), ('music', 'Music'), ('photography', 'Photography'), ('language_learning', 'Language Learning')], max_length=100, verbose_name='Category')),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True, verbose_name='Cover image URL')),
                ('course_data', models.JSONField(verbose_name='Course snapshot data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Version created at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Course owner')),
            ],
            options={
                'verbose_name': 'Course Version',
                'verbose_name_plural': 'Course Versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='CustomLessonType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Lesson type name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('content_schema', models.JSONField(blank=True, default=dict, verbose_name='Content validation schema')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is public type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Usage count')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_lesson_types', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Custom Lesson Type',
                'verbose_name_plural': 'Custom Lesson Types',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Module title')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Module description')),
                ('order', models.PositiveIntegerField(verbose_name='Module order')),
                ('module_structure', models.JSONField(blank=True, default=list, verbose_name='Module structure')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Lesson title')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Lesson description')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('pdf', 'PDF'), ('image', 'Image'), ('link', 'Link'), ('code', 'Code'), ('text', 'Text'), ('custom', 'Custom')], default='text', max_length=50, verbose_name='Lesson content type')),
                ('resources', models.JSONField(blank=True, default=list, verbose_name='Resources')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='Content data')),
                ('order', models.PositiveIntegerField(verbose_name='Lesson order')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='Lesson duration')),
                ('custom_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.customlessontype', verbose_name='Custom lesson type')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Test title')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Test description')),
                ('time_limit', models.PositiveIntegerField(default=0, verbose_name='Time limit (in minutes)')),
                ('count_attempts', models.PositiveIntegerField(default=0, verbose_name='Count attempts')),
                ('pass_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Pass score')),
                ('randomize_questions', models.BooleanField(default=False, verbose_name='Randomize questions')),
                ('show_correct_answers', models.BooleanField(default=True, verbose_name='Show correct answers')),
                ('test_data_ids', models.JSONField(default=list, verbose_name='Mongo question IDs')),
                ('order', models.PositiveIntegerField(verbose_name='Test order')),
                ('is_public', models.BooleanField(db_index=True, default=False, verbose_name='Is public')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_tests', to='courses.course', verbose_name='Course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_tests', to='courses.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('score', models.FloatField(default=0.0, verbose_name='Score')),
                ('passed', models.BooleanField(default=False, verbose_name='Passed')),
                ('answers_data', models.JSONField(default=dict, verbose_name='Answers Data')),
                ('attempt_number', models.PositiveIntegerField(verbose_name='Attempt Number')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.test', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Test Attempt',
                'verbose_name_plural': 'Test Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCourseEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_version', models.PositiveIntegerField(verbose_name='Course version at enrollment')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Enrolled at')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progress')),
                ('module_progress', models.JSONField(blank=True, default=dict, verbose_name='Module progress')),
                ('lesson_progress', models.JSONField(blank=True, default=dict, verbose_name='Lesson progress')),
                ('completed', models.BooleanField(db_index=True, default=False, verbose_name='Completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('time_spent', models.DurationField(default=datetime.timedelta(0), verbose_name='Time spent')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Course Enrollment',
                'verbose_name_plural': 'User Course Enrollments',
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('time_spent', models.DurationField(default=datetime.timedelta(0), verbose_name='Time spent')),
                ('completion_percentage', models.PositiveIntegerField(default=0, verbose_name='Completion percentage')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='courses.lesson', verbose_name='Lesson')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to='courses.usercourseenrollment', verbose_name='Enrollment')),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progresses',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='courses.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'is_published'], name='ix_course_category_published'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['owner', 'is_published'], name='ix_course_owner_published'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-created_at'], name='ix_course_created_desc'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('owner', 'title'), name='unique_course_title_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_published', True), ('published_at__isnull', False)), ('is_published', False), _connector='OR'), name='course_published_requires_timestamp'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user'], name='ix_certificate_user'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_id'], name='ix_certificate_id'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_certificate'),
        ),
        migrations.AddIndex(
            model_name='courseannouncement',
            index=models.Index(fields=['course', '-created_at'], name='ix_announcement_course_created'),
        ),
        migrations.AddIndex(
            model_name='courseannouncement',
            index=models.Index(fields=['is_important'], name='ix_announcement_important'),
        ),
        migrations.AddIndex(
            model_name='coursemeta',
            index=models.Index(fields=['course'], name='ix_meta_course'),
        ),
        migrations.AddIndex(
            model_name='coursemeta',
            index=models.Index(fields=['level'], name='ix_meta_level'),
        ),
        migrations.AddIndex(
            model_name='coursemeta',
            index=models.Index(fields=['-rating'], name='ix_meta_rating_desc'),
        ),
        migrations.AddIndex(
            model_name='coursemeta',
            index=models.Index(fields=['-number_completed'], name='ix_meta_completed_desc'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['course', '-created_at'], name='ix_review_course_created'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['rating'], name='ix_review_rating'),
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_review'),
        ),
        migrations.AddIndex(
            model_name='courseversion',
            index=models.Index(fields=['course_id', 'version_number'], name='ix_version_course_number'),
        ),
        migrations.AddConstraint(
            model_name='courseversion',
            constraint=models.UniqueConstraint(fields=('course_id', 'version_number'), name='unique_course_version'),
        ),
        migrations.AddIndex(
            model_name='customlessontype',
            index=models.Index(fields=['creator'], name='ix_custom_type_creator'),
        ),
        migrations.AddIndex(
            model_name='customlessontype',
            index=models.Index(fields=['is_public'], name='ix_custom_type_public'),
        ),
        migrations.AddIndex(
            model_name='customlessontype',
            index=models.Index(fields=['is_active'], name='ix_custom_type_active'),
        ),
        migrations.AddIndex(
            model_name='customlessontype',
            index=models.Index(fields=['-usage_count'], name='ix_custom_type_usage'),
        ),
        migrations.AddConstraint(
            model_name='customlessontype',
            constraint=models.UniqueConstraint(fields=('creator', 'name'), name='unique_lesson_type_per_creator'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'title'], name='ix_module_course_title'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='ix_module_course_order'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'title'), name='unique_module_title_per_course'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_module_order_per_course'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.CheckConstraint(condition=models.Q(('order__gt', 0)), name='module_order_positive'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'title'], name='ix_lesson_module_title'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='ix_lesson_module_order'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['content_type'], name='ix_lesson_content_type'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'title'), name='unique_lesson_title_per_module'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='unique_lesson_order_per_module'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('order__gt', 0)), name='lesson_order_positive'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(condition=models.Q(('course__isnull', False)), fields=['course', 'title'], name='ix_test_course_title'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(condition=models.Q(('module__isnull', False)), fields=['module', 'title'], name='ix_test_module_title'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(condition=models.Q(('course__isnull', False)), fields=['course', 'order'], name='ix_test_course_order'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(condition=models.Q(('module__isnull', False)), fields=['module', 'order'], name='ix_test_module_order'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['is_public'], name='ix_test_is_public'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', True), ('is_public', True), ('module__isnull', True)), models.Q(('course__isnull', False), ('is_public', False), ('module__isnull', True)), models.Q(('course__isnull', True), ('is_public', False), ('module__isnull', False)), _connector='OR'), name='test_linkage_valid'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('course', 'title'), name='unique_test_title_per_course'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(condition=models.Q(('module__isnull', False)), fields=('module', 'title'), name='unique_test_title_per_module'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('course', 'order'), name='unique_test_order_per_course'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(condition=models.Q(('module__isnull', False)), fields=('module', 'order'), name='unique_test_order_per_module'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(condition=models.Q(('order__gt', 0)), name='test_order_positive'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test'], name='ix_attempt_user_test'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', '-started_at'], name='ix_attempt_test_started'),
        ),
        migrations.AddIndex(
            model_name='usercourseenrollment',
            index=models.Index(fields=['user', 'completed'], name='ix_enrollment_user_completed'),
        ),
        migrations.AddIndex(
            model_name='usercourseenrollment',
            index=models.Index(fields=['course', 'completed'], name='ix_enrollment_course_completed'),
        ),
        migrations.AddIndex(
            model_name='usercourseenrollment',
            index=models.Index(fields=['enrolled_at'], name='ix_enrollment_enrolled_at'),
        ),
        migrations.AddIndex(
            model_name='usercourseenrollment',
            index=models.Index(fields=['progress'], name='ix_enrollment_progress'),
        ),
        migrations.AddIndex(
            model_name='usercourseenrollment',
            index=models.Index(fields=['course_version'], name='ix_enrollment_course_version'),
        ),
        migrations.AddConstraint(
            model_name='usercourseenrollment',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='usercourseenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('completed', False), models.Q(('completed', True), ('completed_at__isnull', False)), _connector='OR'), name='enrollment_completed_requires_timestamp'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['enrollment', 'lesson'], name='ix_progress_enrollment_lesson'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['completed_at'], name='ix_progress_completed_at'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'lesson'), name='unique_lesson_progress_per_enrollment'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', '-added_at'], name='ix_wishlist_user_added'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_wishlist'),
        ),
    ]
