# Generated by Django 5.1.6 on 2025-09-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='certificate',
            table='course_certificates',
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='courseannouncement',
            table='course_announcements',
        ),
        migrations.AlterModelTable(
            name='coursemeta',
            table='course_meta',
        ),
        migrations.AlterModelTable(
            name='coursereview',
            table='course_reviews',
        ),
        migrations.AlterModelTable(
            name='courseversion',
            table='course_versions',
        ),
        migrations.AlterModelTable(
            name='customlessontype',
            table='custom_lesson_types',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='lessons',
        ),
        migrations.AlterModelTable(
            name='lessonprogress',
            table='lesson_progress',
        ),
        migrations.AlterModelTable(
            name='module',
            table='modules',
        ),
        migrations.AlterModelTable(
            name='test',
            table='tests',
        ),
        migrations.AlterModelTable(
            name='testattempt',
            table='test_attempts',
        ),
        migrations.AlterModelTable(
            name='usercourseenrollment',
            table='user_course_enrollments',
        ),
        migrations.AlterModelTable(
            name='wishlist',
            table='user_wishlist',
        ),
    ]
