# Generated by Django 5.1.6 on 2025-09-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_certificate_table_alter_course_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemeta',
            name='feedback',
        ),
        migrations.AddField(
            model_name='coursemeta',
            name='feedback_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='Feedback summary'),
        ),
    ]
