# Generated by Django 5.1.6 on 2025-09-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_test_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemeta',
            name='course_structure',
        ),
        migrations.RemoveField(
            model_name='module',
            name='module_structure',
        ),
    ]
