# Generated by Django 5.1.6 on 2025-09-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_coursemeta_course_structure_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemeta',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='coursemeta',
            name='ix_meta_course',
        ),
        migrations.RemoveIndex(
            model_name='coursemeta',
            name='ix_meta_level',
        ),
        migrations.RemoveIndex(
            model_name='coursemeta',
            name='ix_meta_rating_desc',
        ),
        migrations.RemoveIndex(
            model_name='coursemeta',
            name='ix_meta_completed_desc',
        ),
        migrations.AlterField(
            model_name='coursemeta',
            name='time_to_complete',
            field=models.DurationField(verbose_name='Time to complete course'),
        ),
        migrations.AlterModelTable(
            name='coursemeta',
            table=None,
        ),
    ]
