# Generated by Django 5.1.6 on 2025-09-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_coursemeta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.CharField(blank=True, choices=[('programming', 'Programming'), ('data_science', 'Data Science'), ('design', 'Design'), ('marketing', 'Marketing'), ('business', 'Business'), ('personal_development', 'Personal Development'), ('health_fitness', 'Health & Fitness'), ('music', 'Music'), ('photography', 'Photography'), ('language_learning', 'Language Learning')], db_index=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='test',
            name='level',
            field=models.CharField(blank=True, choices=[('starting', 'Starting'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, max_length=100, null=True, verbose_name='Test level'),
        ),
    ]
