# Generated by Django 5.1.6 on 2025-09-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_test_category_test_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemeta',
            options={'verbose_name': 'Course detail', 'verbose_name_plural': 'Course details'},
        ),
        migrations.AlterField(
            model_name='coursemeta',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, max_length=100, verbose_name='Course level'),
        ),
        migrations.AlterField(
            model_name='test',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, max_length=100, null=True, verbose_name='Test level'),
        ),
        migrations.AddIndex(
            model_name='coursemeta',
            index=models.Index(fields=['course'], name='ix_meta_course'),
        ),
        migrations.AddIndex(
            model_name='coursemeta',
            index=models.Index(fields=['level'], name='ix_meta_level'),
        ),
        migrations.AddIndex(
            model_name='coursemeta',
            index=models.Index(fields=['-rating'], name='ix_meta_rating_desc'),
        ),
        migrations.AddIndex(
            model_name='coursemeta',
            index=models.Index(fields=['-number_completed'], name='ix_meta_completed_desc'),
        ),
        migrations.AlterModelTable(
            name='coursemeta',
            table='course_meta',
        ),
    ]
