# Generated by Django 5.1.6 on 2025-09-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_coursemeta_options_alter_coursemeta_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Updated at'),
        ),
    ]
