# Generated by Django 5.1.6 on 2025-09-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='Test description'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_data_ids',
            field=models.CharField(max_length=24, unique=True, verbose_name='Mongo document ID'),
        ),
    ]
