# Generated by Django 5.1.6 on 2025-09-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_test_description_alter_test_test_data_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='structure_ids',
            field=models.CharField(default='', max_length=24, unique=True, verbose_name='Mongo id for course structure'),
        ),
        migrations.AddField(
            model_name='module',
            name='structure_ids',
            field=models.CharField(default='', max_length=24, unique=True, verbose_name='Mongo id for module structure'),
        ),
    ]
