# Generated by Django 5.1.6 on 2025-09-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_structure_ids_module_structure_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.AlterField(
            model_name='course',
            name='structure_ids',
            field=models.CharField(max_length=24, unique=True, verbose_name='Mongo id for course structure'),
        ),
        migrations.AlterField(
            model_name='module',
            name='structure_ids',
            field=models.CharField(max_length=24, unique=True, verbose_name='Mongo id for module structure'),
        ),
    ]
