# Generated by Django 5.1.6 on 2025-12-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_module_description_alter_course_structure_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='custom_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='resources',
        ),
        migrations.AddField(
            model_name='lesson',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, max_length=7000, verbose_name='Content (Markdown)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('presentation', 'Presentation'), ('link', 'Link'), ('custom', 'Custom')], default='text', max_length=50, verbose_name='Lesson content type'),
        ),
        migrations.DeleteModel(
            name='CustomLessonType',
        ),
    ]
