# Generated by Django 5.1.6 on 2025-12-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_lesson_custom_type_remove_lesson_resources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='comment',
        ),
    ]
