# Generated by Django 5.1.6 on 2026-01-29 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_lesson_comment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='testattempt',
            name='ix_attempt_user_test',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='answers_data',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercourseenrollment',
            name='lesson_progress',
        ),
        migrations.RemoveField(
            model_name='usercourseenrollment',
            name='module_progress',
        ),
        migrations.AddField(
            model_name='testattempt',
            name='attempt_details',
            field=models.JSONField(blank=True, default=list, verbose_name='Attempt Details'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='enrollment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='courses.usercourseenrollment', verbose_name='Enrollment'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['enrollment', 'test'], name='ix_attempt_enrollment_test'),
        ),
    ]
