# Generated by Django 5.1.6 on 2026-01-31 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_testattempt_ix_attempt_user_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='courses.usercourseenrollment', verbose_name='Enrollment'),
        ),
    ]
