# Generated by Django 5.1.6 on 2026-02-02 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_testattempt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Time spent'),
        ),
    ]
