# Generated by Django 5.1.6 on 2026-02-02 23:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_testattempt_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Completed at'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='started_at',
            field=models.DateTimeField(verbose_name='Started at'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Completed at'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='started_at',
            field=models.DateTimeField(verbose_name='Started at'),
        ),
    ]
