# Generated by Django 5.1.6 on 2026-02-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_lessonprogress_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed at'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started at'),
        ),
    ]
