# Generated by Django 5.1.6 on 2026-03-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_lessonprogress_completed_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseAnnouncement',
        ),
    ]
