export { getInitials, getAchievementColor } from './utils'
export { achievements, courseProgress, learningStats } from './mock-data'
export * from './i18n'
export * from './cookies'
export * from './csrf'
