# Generated by Django 5.1.6 on 2026-03-19 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0021_alter_lessonprogress_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUserCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to=settings.AUTH_USER_MODEL, verbose_name='Calendar owner')),
            ],
            options={
                'verbose_name': 'User calendar',
                'verbose_name_plural': 'User calendars',
                'db_table': 'user_calendars',
            },
        ),
        migrations.CreateModel(
            name='CourseCalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateTimeField(verbose_name='Event date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_events', to='users_calendar.baseusercalendar', verbose_name='Calendar')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course event',
                'verbose_name_plural': 'Course events',
                'db_table': 'course_events',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='PersonalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateTimeField(verbose_name='Event date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('importance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Importance')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_events', to='users_calendar.baseusercalendar', verbose_name='Calendar')),
            ],
            options={
                'verbose_name': 'Personal event',
                'verbose_name_plural': 'Personal events',
                'db_table': 'personal_events',
                'ordering': ['event_date'],
            },
        ),
    ]
