# Generated by Django 5.1.6 on 2026-03-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_lessonprogress_completed_at_and_more'),
        ('users_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecalendarevent',
            name='event_date',
            field=models.DateTimeField(db_index=True, verbose_name='Event date'),
        ),
        migrations.AlterField(
            model_name='personalevent',
            name='event_date',
            field=models.DateTimeField(db_index=True, verbose_name='Event date'),
        ),
        migrations.AddIndex(
            model_name='coursecalendarevent',
            index=models.Index(fields=['calendar', 'event_date'], name='course_even_calenda_6c9ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='personalevent',
            index=models.Index(fields=['calendar', 'event_date'], name='personal_ev_calenda_b30ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='personalevent',
            index=models.Index(fields=['is_completed'], name='personal_ev_is_comp_03afc8_idx'),
        ),
    ]
