# Generated by Django 5.1.6 on 2026-03-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_calendar', '0002_alter_coursecalendarevent_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalevent',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
    ]
