# Generated by Django 5.1.6 on 2026-03-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_calendar', '0003_alter_personalevent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalevent',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Description'),
        ),
    ]
