# Generated by Django 5.1.6 on 2026-03-23 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_lessonprogress_completed_at_and_more'),
        ('users_calendar', '0004_alter_personalevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecalendarevent',
            name='course_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_test_events', to='courses.test'),
        ),
        migrations.AddField(
            model_name='coursecalendarevent',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is completed'),
        ),
        migrations.AddField(
            model_name='coursecalendarevent',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='coursecalendarevent',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='coursecalendarevent',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.module'),
        ),
        migrations.AddField(
            model_name='coursecalendarevent',
            name='module_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_test_events', to='courses.test'),
        ),
    ]
