# Generated by Django 5.1.6 on 2025-07-28 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_picture', models.URLField(blank=True, max_length=500, null=True, verbose_name='Profile Picture')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('organization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organization')),
                ('specialization', models.CharField(blank=True, max_length=150, null=True, verbose_name='Specialization')),
                ('education_level', models.CharField(blank=True, choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('doctor of science', 'Doctor of Science'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=100, null=True, verbose_name='Education Level')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='About me')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email notifications')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push notifications')),
                ('deadline_reminders', models.BooleanField(default=True, verbose_name='Deadline reminders')),
                ('show_profile_to_others', models.BooleanField(default=True, verbose_name='Show profile to others')),
                ('show_achievements', models.BooleanField(default=True, verbose_name='Show achievements')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
