# Generated by Django 5.1.6 on 2025-09-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_email_c80f75_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified_email',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is email verified'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('teacher', 'Teacher')], db_index=True, max_length=50, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('doctor of science', 'Doctor of Science'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], db_index=True, max_length=100, null=True, verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Profile Picture URL'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='show_profile_to_others',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Show profile to others'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active', 'is_verified_email'], name='users_custo_is_acti_a410f4_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email', 'is_active'], name='users_custo_email_1a70ed_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'is_active'], name='users_custo_role_e4c2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['created_at', 'is_active'], name='users_custo_created_41cf87_idx'),
        ),
    ]
