# Generated by Django 5.1.6 on 2025-09-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_users_custo_email_c80f75_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customuser',
            new_name='users_is_acti_19c69c_idx',
            old_name='users_custo_is_acti_a410f4_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='users_email_a7cfd1_idx',
            old_name='users_custo_email_1a70ed_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='users_role_a8f2ba_idx',
            old_name='users_custo_role_e4c2f2_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='users_created_dcdedc_idx',
            old_name='users_custo_created_41cf87_idx',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='users_profiles',
        ),
        migrations.AlterModelTable(
            name='usersettings',
            table='users_settings',
        ),
    ]
